### PR TITLE
Adapt release following fstab/docker-grok_exporter-compiler#1

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by fstab** [comment]
Sounds like a good idea, I will try it as soon as possible.

**Comment by fstab** [comment]
Thanks!!!

**Comment by fstab** [comment]
Released `v0.2.3` using your PR to [fstab/grok_exporter-compiler](https://hub.docker.com/r/fstab/grok_exporter-compiler). The release also supports a `retention` configuration for metrics.

**Comment by roidelapluie** [comment]
Awesome

**Pull request merged**
