### PR TITLE
fix freebsd i386 compile error

### PR DESCRIPTION
**Pull request by flachesis**
* fix issue: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=224455#c3

### CODE REVIEW

**Comment by fstab** [comment]
Thanks a lot for the fix! I think it's worthwhile to make the implementation a bit more verbose and replace the unsafe pointers with explicit types. If you create two architecture-specific files:

`tailer/fileTailer_darwin_386.go`:

```go
package tailer

func fdToInt(fd uintptr) uint32 {
        return uint32(fd)
}
```

`tailer/fileTailer_darwin_amd64.go`:

```go
package tailer

func fdToInt(fd uintptr) uint64 {
        return uint64(fd)
}
```

you can replace all `uint64(fd.File())` with `fdToInt(file.Fd())` and you don't need the unsafe pointers. It's a trade-off: two more files vs. unsafe pointers. I think getting rid of unsafe pointers is worth two more files.

**Comment by flachesis** [comment]
help review again, thanks~

**Comment by fstab** [comment]
I think there is a misunderstanding. I didn't mean to copy the entire file `fileTailer_darwin.go`. Please keep the file as it is, and create `fileTailer_darwin_386.go` and `fileTailer_darwin_amd64.go` with just one single function `fdToInt()`.

**Comment by flachesis** [comment]
ci build fail, but i don't know why?

**Comment by flachesis** [comment]
I send pr again and close this.

**Pull request closed without merging**
