### PR TITLE
Kafka tailer integration

### PR DESCRIPTION
**Pull request by hartfordfive**
Here's the Kafka tailer integration as discussed in the other [stale PR](https://github.com/fstab/grok_exporter/pull/16).  Please note I've also vendored in all the related dependencies.

### CODE REVIEW

**Comment by fstab** [comment]
Thanks a lot! I don't think it's necessary to add the `vendor/` directory, because `go.mod` and `go.sum` already contain all required information for reproducible builds, and you can always generate the `vendor/` directory with `go mod vendor`. Please remove it.

**Comment by hartfordfive** [comment]
@fstab  I've gone ahead and deleted the vendor directory.   

As a bit of context for you, I've encountered situations in the past where a repo was no longer available or moved, which was very problematic.  Consequently, this is why I often vendor my dependencies so there is always a guarantee I can rebuild a given version with only the application repo.  In some cases, certain industries may have requirements to store the source code of opensource projects used (especially if they are complementing some other proprietary software) in case of a future audit, for example, trading firms in the finance industry.

I hope this provides a bit of clarity as to why I initially did this!

**Comment by fstab** [comment]
Thanks a lot! I merged it. I will make a release soon.

Your comments on reproducible builds make sense. However, I'm not sure if committing all dependencies to the source repository is the best solution. Maybe I should provide a vendor source tar with each release or something like that.

**Comment by hartfordfive** [comment]
Yes, having a separate build that would also include the vendor build sounds like a great idea to me.

**Comment by fstab** [comment]
I thought again about adding the `vendor/` folder for making builds reproducible. I think you are right. I added the `vendor/` folder with 1.0.0.RC5.

**Pull request merged**
