### PR TITLE
add 32 bit arm support

### PR DESCRIPTION
**Pull request by geekdave**
Companion PR for https://github.com/fstab/docker-grok_exporter-compiler/pull/2

Note that for some reason I could not get the tests to work, hence tests are commented out.  I lost the console output for what happened exactly, but I can try to reproduce this on a fresh pi in the next few days if it would be helpful.

### CODE REVIEW

**Comment by fstab** [comment]
`grok_exporter` on the raspberry, that sounds great. Thanks a lot. I will set up my raspberry and try it.

**Comment by fstab** [comment]
I finally found the time to set up a virtual raspberry pi with `qemu` for testing. Unfortunately, `grok_exporter` terminates with this error right after start:
```
Illegal instruction
```
My guess is this is because my emulation uses arm32v6 while the build produces arm32v7. There seems to be no straightforward way to build an ARMv6 version. There are Docker images for v6, but they are all based on Alpine linux, so `grok_exporter` ends up being linked against musl libc instead of glibc. This means the binaries will not run on Raspbian which uses glibc.

Need to look into this a bit more.

**Comment by fstab** [comment]
I found that [resin/rpi-raspbian](https://hub.docker.com/r/resin/rpi-raspbian/) has ARM32v6 support. Used this as the base image. Now everything seems to work. Added `grok_exporter-0.2.6.linux-arm32v6.zip` to the current [v0.2.6 release](https://github.com/fstab/grok_exporter/releases).

**Comment by geekdave** [comment]
@fstab forgot to say thanks so much for this! It’s working perfectly on my pi. Related question: I’ve created a docker image of this for easier distribution and management. Before I publish my own bespoke image to docker hub I was wondering if you would consider an official docker image?

**Comment by fstab** [comment]
I'd be happy if you publish it.

Note that the resin/rpi-raspbian image is no longer maintained, so I switched to dockcross/linux-armv6 in the current version of [fstab/docker-grok_exporter-compiler](https://github.com/fstab/docker-grok_exporter-compiler).

**Pull request merged**
