### PR TITLE
add template function to shift decimal points

### PR DESCRIPTION
**Pull request by mmolnar**
This function will be usefull when you need to convert miliseconds to seconds.

I am not a go programmer, so doing tests would be difficult for me.

### CODE REVIEW

**Comment by fstab** [comment]
Looks good, thanks. Maybe it would be clearer to use `multiply` instead of `shift`. With `{{shift .val 3}}` there are some implicit assumptions (decimal shift (not binary), shift is to the right (not to the left), order of the parameters is important (right is the exponent)). If we instead implement `{{multiply .val 1000}}` I think it would be clearer what it does.

Could you change it and make it `multiply` instead of `shift`?

**Comment by mmolnar** [comment]
OK, I have modified the commit to do general multiplication.
As templates can use go float literals I can just use scientific notation simply achieve what I was aiming for:
`{{multiply .val 1.e-6}}`

**Comment by fstab** [comment]
Thanks!

**Comment by fstab** [comment]
I added add, subtract, and divide. So we have all four arithmetic functions now.

**Pull request merged**
