### PR TITLE
Added Webhook Input Type Support

### PR DESCRIPTION
**Pull request by dcwangmit01**

### CODE REVIEW

**Comment by fstab** [comment]
Thanks for the PR. I'm mostly offline until Wednesday and will have a look after that.

**Comment by dcwangmit01** [comment]
Thanks @fstab

Force push was to fix some test issues.  Tests are still failing in CI.  Unable to reproduce CI test failures on my system.

**Comment by fstab** [comment]
Great PR, thanks! The failing tests on Windows are not related to the PR.

**Comment by dcwangmit01** [comment]
Thanks for merging this.

**Pull request merged**
